### ISSUE TITLE
Uncaught TypeError: PIXI.SimplePlane is not a constructor

### ISSUE THREAD

**Issue by joao-cesar** [pixijs-userland/animate#108]
Hi.

When I try to create a SimplePlane I get this error.

Does this Animate extension use a PIXI subset?

**Comment by andrewstart** [comment]
The Animate package doesn't use SimplePlane or any other type of Mesh. I believe your error (that you forgot to include) is unrelated.

**Comment by joao-cesar** [comment]
Hi. Thanks.

The error is in the title:

Uncaught TypeError: PIXI.SimplePlane is not a constructor
    at Object.<anonymous> (pixi_game.js:32)
    at Object._setTimelinePosition (MovieClip.js:927)
    at Object._setTimelinePosition (MovieClip.js:847)
    at Object._updateTimeline (MovieClip.js:809)
    at Object.advance (MovieClip.js:742)
    at Object._tickListener (MovieClip.js:286)
    at TickerListener.emit (TickerListener.js:78)
    at Ticker.update (Ticker.js:394)
    at Ticker._tick (Ticker.js:113)

I'm just trying to recreate [this example](https://pixijs.io/examples/#/demos-basic/simpleplane.js) to simulate a water ripple effect.

So there is no way to use the SimplePlane or any other type of mesh even if I provide the bitmap?

**Comment by bigtimebuddy** [comment]
Please show more. How you import/build/run your project matters and there no information in your issue about what your doing. It's hard to give you helpful feedback if you provide so little.

**Comment by joao-cesar** [comment]
My code is in the first frame of the main timeline.

`// 'water' is the name of a Movie Clip instance on the stage
// and there's a bitmap inside of it
const texture = this.water.children[0];
const verticesX = 10;
const verticesY = 10;
const plane = new PIXI.SimplePlane(texture, verticesX, verticesY);
let buffer;

plane.x = 100;
plane.y = 100;
this.addChild(plane);
buffer = plane.geometry.getBuffer('aVertexPosition');

scene.ticker.add((delta) =>
{
    for (let i = 0; i < buffer.data.length; i++)
		buffer.data[i] += (Math.random() - 0.5);
		
    buffer.update();
});`

I'm the default test command of Animate (Ctrl/Cmd + Enter (Num)).

I have a Movie Clip instance on stage called water and a bitmap inside of it. I'm using this bitmap as the texture for the SimplePlan instance.

![image](https://user-images.githubusercontent.com/24843493/139505141-05586885-b79a-46a3-b16d-561e2e0ea682.png)

![image](https://user-images.githubusercontent.com/24843493/139505185-2a4e7427-90e0-4465-9fec-d727f3495b27.png)

![image](https://user-images.githubusercontent.com/24843493/139505209-0a9e0787-6837-4e79-bc53-e0f76fa27ae7.png)

I'm just trying to reproduce this example:
https://pixijs.io/examples/#/demos-basic/simpleplane.js

**Comment by andrewstart** [comment]
It looks like the latest version of the extension might not have made it to Adobe Exchange, so please make sure you've manually installed the latest release, and make sure that your publish settings say that you are publishing for Pixi Animate v2 and PixiJS v6.

Once you get that sorted out, you'll want to read the `texture` property off of `this.water.children[0]`, as a Sprite on the display tree isn't a texture that you can pass to a mesh.

**Comment by joao-cesar** [comment]
Hi, @andrewstart!

Thanks a lot. I did what you suggested and now it's working.

I just cannot figure it out how to access the current Application object to add a tick even to it... My workaround now is to use the regular requestAnimationFrame approach, but I suppose PIXI does some optimizations if we use the ticker approach.
